-- run_test.py: invoking following command in '/workspaces/isaac_ros-dev/isaac_ros_nitros/isaac_ros_managed_nitros_examples/custom_nitros_image':
 - /opt/ros/humble/bin/ament_flake8 --xunit-file /workspaces/isaac_ros-dev/build/custom_nitros_image/test_results/custom_nitros_image/flake8.xunit.xml


3 files checked
No problems found

Checked files:

* ./test/custom_nitros_image_builder_pol.py
* ./test/custom_nitros_image_pol.py
* ./test/custom_nitros_image_viewer_pol.py


-- run_test.py: return code 0
-- run_test.py: verify result file '/workspaces/isaac_ros-dev/build/custom_nitros_image/test_results/custom_nitros_image/flake8.xunit.xml'
